services:
    neo4j:
        image: neo4j:5-community
        container_name: neo4j_container
        ports:
            - "7474:7474"
            - "7687:7687"
        restart: unless-stopped
        environment:
            NEO4J_AUTH: none
            # Las siguientes son opciones para el ajuste en caso de que los recursos
            # asignados por defecto sean insuficientes
            #NEO4J_server_memory_heap_initial__size: 4G
            #NEO4J_server_memory_heap_max__size: 4G
            #NEO4J_dbms_import_csv_buffer__size: 209715200
            #NEO4J_dbms_memory_transaction_total_max: 4G
        
        volumes:
            - neo4j-volume:/data

volumes:
    neo4j-volume: